import { HouseDesign } from '../types';

export const UPSELL_OPTIONS = [
  { id: 'extra-renders', label: 'Dodatni renderi', description: '5 dodatnih 3D vizualizacija eksterijera i interijera', price: 15 },
  { id: 'floor-plan', label: 'Prilagodba tlocrta', description: 'Jedna prilagodba rasporeda prostorija prema vašim željama', price: 30 },
  { id: 'investor-pack', label: 'Paket za investitore', description: 'ROI analiza, troškovnik gradnje i prezentacijski materijal', price: 20 },
];

export const MOCK_HOUSES: HouseDesign[] = [
  // Alpine (6)
  {
    id: '1',
    title: 'Forest Frame A1',
    description: 'Moderna A-Frame kuća savršena za šumske predjele. Velike staklene stijene koje spajaju unutrašnjost s prirodom. Idealna za vikend odmor ili stalno stanovanje u mirnom ambijentu.',
    price: 85,
    sqMeters: 85,
    bedrooms: 2,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=800&auto=format&fit=crop',
    category: 'Alpski',
    featured: true,
    floors: 2,
    garage: false,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 18,
    features: ['Terasa', 'Kaminska peć', 'Panoramski prozori', 'Drvena fasada', 'Podna grijanja'],
    images: [
      'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1587061949409-02df41d5e562?q=80&w=800&auto=format&fit=crop',
    ],
  },
  {
    id: '2',
    title: 'Alpine Lodge',
    description: 'Tradicionalni stil s modernim elementima. Prostrani dnevni boravak s pogledom na planine. Savršena kombinacija udobnosti i prirodnog okruženja.',
    price: 72,
    sqMeters: 110,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?q=80&w=800&auto=format&fit=crop',
    category: 'Alpski',
    featured: true,
    floors: 2,
    garage: true,
    energyClass: 'B',
    kitchen: true,
    terraceArea: 25,
    floorPlanUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?q=80&w=800&auto=format&fit=crop',
    features: ['Garaža', 'Terasa', 'Ostava', 'Drvo-pelet kotlovnica'],
    images: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=800&auto=format&fit=crop',
    ],
  },
  {
    id: '3',
    title: 'Chalet Alpino',
    description: 'Klasični švicarski šalet s drvenim balkonima i panoramskim pogledom na alpski pejzaž.',
    price: 95,
    sqMeters: 130,
    bedrooms: 4,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?q=80&w=800&auto=format&fit=crop',
    category: 'Alpski',
    floors: 2,
    garage: true,
    energyClass: 'A+',
    kitchen: true,
    terraceArea: 30,
    features: ['Balkon', 'Podrum', 'Garaža', 'Sauna', 'Kamin'],
  },
  {
    id: '4',
    title: 'Mountain Barn',
    description: 'Rustikalni barn konvertiran u modernu kuću za odmor s visokim stropovima.',
    price: 68,
    sqMeters: 95,
    bedrooms: 2,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=800&auto=format&fit=crop',
    category: 'Alpski',
    floors: 1,
    garage: false,
    energyClass: 'B',
    kitchen: true,
    terraceArea: 12,
    features: ['Visoki stropovi', 'Otvoreni plan', 'Kamin'],
  },
  {
    id: '5',
    title: 'Snow Peak Cabin',
    description: 'Kompaktna planinska koliba s kaminom i pogledom na vrhove.',
    price: 55,
    sqMeters: 60,
    bedrooms: 2,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?q=80&w=800&auto=format&fit=crop',
    category: 'Alpski',
    floors: 1,
    garage: false,
    energyClass: 'B',
    kitchen: true,
    terraceArea: 10,
    features: ['Kamin', 'Terasa', 'Drvo-pelet grijanje'],
  },
  {
    id: '6',
    title: 'Timber Ridge',
    description: 'Drvena kuća na padini s terasom i panoramskim prozorom.',
    price: 78,
    sqMeters: 100,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=800&auto=format&fit=crop',
    category: 'Alpski',
    floors: 2,
    garage: false,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 20,
    features: ['Terasa', 'Panoramski prozori', 'Drvena fasada'],
  },

  // Modern (6)
  {
    id: '7',
    title: 'Nordic Cube',
    description: 'Minimalistička kocka, drvena fasada, energetski učinkovita. Skandinavski dizajn prilagođen lokalnoj klimi s naglaskom na funkcionalnost i estetiku.',
    price: 63,
    sqMeters: 65,
    bedrooms: 1,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?q=80&w=800&auto=format&fit=crop',
    category: 'Moderni',
    featured: true,
    floors: 1,
    garage: false,
    energyClass: 'A+',
    kitchen: true,
    terraceArea: 8,
    features: ['Ravni krov', 'Solarna energija', 'Rekuperacija zraka', 'Toplinska pumpa'],
  },
  {
    id: '8',
    title: 'Glass Haven',
    description: 'Staklena vila s otvorenim tlocrtom i minimalističkim interijerom.',
    price: 99,
    sqMeters: 140,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=800&auto=format&fit=crop',
    category: 'Moderni',
    featured: true,
    floors: 2,
    garage: true,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 40,
    floorPlanUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=800&auto=format&fit=crop',
    features: ['Garaža', 'Krovne terase', 'Automatizacija doma', 'Infinity bazen'],
  },
  {
    id: '9',
    title: 'Black Box',
    description: 'Crna monolitna kuća s kontrastnim bijelim interijerom.',
    price: 74,
    sqMeters: 90,
    bedrooms: 2,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?q=80&w=800&auto=format&fit=crop',
    category: 'Moderni',
    floors: 2,
    garage: false,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 15,
    features: ['Ravni krov', 'Minimalistički dizajn', 'Solarna energija'],
  },
  {
    id: '10',
    title: 'White Minimal',
    description: 'Bijela kuća s ravnim krovom, čiste linije i veliki prozori.',
    price: 88,
    sqMeters: 115,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=800&auto=format&fit=crop',
    category: 'Moderni',
    floors: 2,
    garage: true,
    energyClass: 'A+',
    kitchen: true,
    terraceArea: 22,
    features: ['Garaža', 'Terasa', 'Toplinska pumpa', 'Podna grijanja'],
  },
  {
    id: '11',
    title: 'Steel & Wood',
    description: 'Kombinacija čelika i drveta u modernoj arhitekturi.',
    price: 67,
    sqMeters: 80,
    bedrooms: 2,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=800&auto=format&fit=crop',
    category: 'Moderni',
    floors: 1,
    garage: false,
    energyClass: 'B',
    kitchen: true,
    terraceArea: 16,
    features: ['Otvoreni plan', 'Drvena terasa', 'Čelična konstrukcija'],
  },
  {
    id: '12',
    title: 'Urban Retreat',
    description: 'Gradski stil prilagođen ruralnom okruženju s krovnom terasom.',
    price: 91,
    sqMeters: 105,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop',
    category: 'Moderni',
    floors: 2,
    garage: true,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 28,
    features: ['Krovne terase', 'Garaža', 'Automatizacija doma'],
  },

  // Mediterranean (6)
  {
    id: '13',
    title: 'Mediteran Lux',
    description: 'Ravni krovovi, kamen i bijela fasada. Dizajnirano za sunčane dane. Prostrani vanjski prostori s pergolom i mediteranskim vrtom stvaraju savršenu atmosferu.',
    price: 97,
    sqMeters: 120,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?q=80&w=800&auto=format&fit=crop',
    category: 'Mediteranski',
    featured: true,
    floors: 2,
    garage: false,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 35,
    features: ['Pergola', 'Kamena fasada', 'Vanjska kuhinja', 'Mediteranski vrt'],
  },
  {
    id: '14',
    title: 'Santorini Dreams',
    description: 'Inspirirana grčkim otocima – bijeli zidovi, plave kupole i infinity bazen.',
    price: 100,
    sqMeters: 160,
    bedrooms: 4,
    bathrooms: 3,
    imageUrl: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=800&auto=format&fit=crop',
    category: 'Mediteranski',
    featured: true,
    floors: 2,
    garage: true,
    energyClass: 'A+',
    kitchen: true,
    terraceArea: 50,
    floorPlanUrl: 'https://images.unsplash.com/photo-1503174971373-b1f69850bded?q=80&w=800&auto=format&fit=crop',
    features: ['Infinity bazen', 'Krovne terase', 'Garaža', 'Vanjska kuhinja'],
  },
  {
    id: '15',
    title: 'Costa Villa',
    description: 'Obalna vila s terasom, pergolom i pogledom na more.',
    price: 82,
    sqMeters: 145,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=800&auto=format&fit=crop',
    category: 'Mediteranski',
    floors: 2,
    garage: false,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 45,
    features: ['Terasa', 'Pergola', 'Bazenska terasa', 'Vanjska kuhinja'],
  },
  {
    id: '16',
    title: 'Olive Garden House',
    description: 'Kamena kuća okružena maslinicima s rustikalnim šarmom.',
    price: 59,
    sqMeters: 90,
    bedrooms: 2,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=800&auto=format&fit=crop',
    category: 'Mediteranski',
    floors: 1,
    garage: false,
    energyClass: 'B',
    kitchen: true,
    terraceArea: 14,
    features: ['Kamena fasada', 'Terasa', 'Rustikalni stil'],
  },
  {
    id: '17',
    title: 'Terra Rossa',
    description: 'Toskanski stil s crvenom terakotom i arkadama.',
    price: 76,
    sqMeters: 125,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1523217582562-09d0def993a6?q=80&w=800&auto=format&fit=crop',
    category: 'Mediteranski',
    floors: 2,
    garage: false,
    energyClass: 'B',
    kitchen: true,
    terraceArea: 24,
    features: ['Arkade', 'Terakota pod', 'Unutarnje dvorište'],
    images: [
      'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?q=80&w=800&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?q=80&w=800&auto=format&fit=crop',
    ],
  },
  {
    id: '18',
    title: 'Adriatic Pearl',
    description: 'Moderna interpretacija dalmatinske kuće s vanjskom kuhinjom.',
    price: 86,
    sqMeters: 100,
    bedrooms: 2,
    bathrooms: 2,
    imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=800&auto=format&fit=crop',
    category: 'Mediteranski',
    floors: 2,
    garage: false,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 32,
    features: ['Vanjska kuhinja', 'Krovne terase', 'Kamena fasada'],
  },

  // Tiny House (6)
  {
    id: '19',
    title: 'Tiny Escape',
    description: 'Kompaktno rješenje na kotačima ili temeljima. Sve što vam treba u 25m². Pametno dizajnirani prostori koji maksimiziraju udobnost uz minimalan otisak.',
    price: 50,
    sqMeters: 25,
    bedrooms: 1,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=800&auto=format&fit=crop',
    category: 'Mala Kuća',
    featured: true,
    floors: 1,
    garage: false,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 6,
    features: ['Solarna energija', 'Rasklopivi namještaj', 'Mobilna platforma', 'Kompost toalet'],
  },
  {
    id: '20',
    title: 'Forest Pod',
    description: 'Okrugli pod smješten u šumi, dizajniran s minimalnim otpadom.',
    price: 64,
    sqMeters: 30,
    bedrooms: 1,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?q=80&w=800&auto=format&fit=crop',
    category: 'Mala Kuća',
    featured: true,
    floors: 1,
    garage: false,
    energyClass: 'A+',
    kitchen: true,
    terraceArea: 8,
    floorPlanUrl: 'https://images.unsplash.com/photo-1626885930974-4b69aa21bbf9?q=80&w=800&auto=format&fit=crop',
    features: ['Okrugla forma', 'Solarna energija', 'Zeleni krov'],
  },
  {
    id: '21',
    title: 'Container Home',
    description: 'Modificiran kontejner pretvoren u udoban dom za odmor.',
    price: 70,
    sqMeters: 35,
    bedrooms: 1,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=800&auto=format&fit=crop',
    category: 'Mala Kuća',
    floors: 1,
    garage: false,
    energyClass: 'B',
    kitchen: true,
    terraceArea: 10,
    features: ['Industrijski stil', 'Modularna gradnja', 'Terasa'],
  },
  {
    id: '22',
    title: 'Tree Loft',
    description: 'Kuća na drvetu s modernim komforom i drvenim mostom.',
    price: 58,
    sqMeters: 28,
    bedrooms: 1,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=800&auto=format&fit=crop',
    category: 'Mala Kuća',
    floors: 1,
    garage: false,
    energyClass: 'B',
    kitchen: true,
    terraceArea: 5,
    features: ['Kuća na drvetu', 'Drveni most', 'Terasa'],
  },
  {
    id: '23',
    title: 'Glass Cabin',
    description: 'Staklena kabina u prirodi za potpuno uranjanje u okoliš.',
    price: 73,
    sqMeters: 40,
    bedrooms: 1,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=800&auto=format&fit=crop',
    category: 'Mala Kuća',
    floors: 1,
    garage: false,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 12,
    features: ['Staklene stijene', 'Prirodna ventilacija', 'Terasa'],
  },
  {
    id: '24',
    title: 'Micro Lodge',
    description: 'Pametan raspored prostora s rasklopivim namještajem i solarnom energijom.',
    price: 53,
    sqMeters: 22,
    bedrooms: 1,
    bathrooms: 1,
    imageUrl: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=800&auto=format&fit=crop',
    category: 'Mala Kuća',
    floors: 1,
    garage: false,
    energyClass: 'A+',
    kitchen: true,
    terraceArea: 4,
    features: ['Rasklopivi namještaj', 'Solarna energija', 'Pametno skladištenje'],
  },
  {
    id: '25',
    title: 'Moderni Farmhouse 4 Sobe',
    description: 'Savršeno uravnotežen moderni farmhouse s otvorenim planom dnevnog boravka, velikom kuhinjom i prostornim spavaćim sobama. Idealan za porodice koje cijene moderan dizajn i funkcionalnost.',
    price: 89,
    sqMeters: 223,
    bedrooms: 4,
    bathrooms: 3,
    imageUrl: 'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/325005828/original/56478SM_Render001_1709224227.jpg',
    category: 'Moderni',
    featured: true,
    floors: 1,
    garage: true,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 38,
    features: ['Otvoreni plan', 'Moderna kuhinja', '3 garaže', 'Prostrana terasa', 'Energetski učinkovit'],
    images: [
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/325005828/original/56478SM_stills_001_1611268832.jpg',
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/325005828/original/56478SM_stills_002_1611268832.jpg',
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/325005828/original/56478SM_stills_003_1611268833.jpg',
    ],
  },
  {
    id: '26',
    title: 'Moderni Farmhouse s Radioničnom Garažom',
    description: 'Elegantni moderni farmhouse s velikom radioničnom garažom, savršen za entuzijaste i majstore. Prostrani interijer s modernim finišima i funkcionalnim rasporedom.',
    price: 79,
    sqMeters: 232,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/385367739/original/52031HZ-001-Exterior-Render_1771338924.jpg',
    category: 'Moderni',
    featured: true,
    floors: 1,
    garage: true,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 26,
    floorPlanUrl: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?q=80&w=800&auto=format&fit=crop',
    features: ['Radionična garaža', 'Otvoreni plan', 'Moderna kuhinja', 'Terasa', 'Mudroom'],
    images: [
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/385367739/original/52031HZ-002-Exterior-Render_1771338924.jpg',
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/385367739/original/52031HZ-003-Exterior-Render_1771338924.jpg',
    ],
  },
  {
    id: '27',
    title: 'Moderni Alpski Dom s Pogledom na Planine',
    description: 'Spektakularni alpski dom s modernom arhitekturom, velikim prozorima koji pružaju pogled na planine i prostornim životnim prostorom na dva sprata.',
    price: 95,
    sqMeters: 203,
    bedrooms: 4,
    bathrooms: 2,
    imageUrl: 'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/384595708/original/623600DJ-001-Exterior-Renders_1769787872.jpg',
    category: 'Alpski',
    featured: true,
    floors: 2,
    garage: true,
    energyClass: 'A+',
    kitchen: true,
    terraceArea: 42,
    features: ['Panoramski prozori', 'Pogled na planine', 'Moderna arhitektura', 'Garaža', 'Balkon'],
    images: [
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/384595708/original/623600DJ-002-Exterior-Renders_1769787873.jpg',
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/384595708/original/623600DJ-003-Exterior-Renders_1769787873.jpg',
    ],
  },
  {
    id: '28',
    title: 'Alpska Kuća s Kamenom Fasadom',
    description: 'Tradicionalna alpska kuća s autentičnom kamenom fasadom i modernim interijjerom. Savršena harmonija između prirodnih materijala i savremenog komfora.',
    price: 75,
    sqMeters: 207,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/384458440/original/61703UT-001-Exterior-Image_1770233022.jpg',
    category: 'Alpski',
    floors: 1,
    garage: true,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 32,
    features: ['Kamena fasada', 'Garaža', 'Terasa', 'Drveni elementi', 'Podno grijanje'],
    images: [
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/384458440/original/61703UT-002-Exterior-Image_1770233023.jpg',
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/384458440/original/61703UT-003-Exterior-Image_1770233025.jpg',
    ],
  },
  {
    id: '29',
    title: 'Mediteranska Vila s Kamenim Lukom',
    description: 'Luksuzna mediteranska vila s karakterističnim kamenim lukovima, toplim tonovima i otvorenim prostorom koji spaja unutrašnjost s terasom i vrtom.',
    price: 85,
    sqMeters: 226,
    bedrooms: 4,
    bathrooms: 3,
    imageUrl: 'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/384540789/original/910124WHD-001-Exterior%20Image_1770400544.jpg',
    category: 'Mediteranski',
    featured: true,
    floors: 1,
    garage: true,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 55,
    features: ['Kameni lukovi', 'Prostrana terasa', 'Mediteranski vrt', 'Otvoreni plan', 'Garaža'],
    images: [
      'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/384540789/original/910124WHD-Front-Elevation_1770400506.jpg',
    ],
  },
  {
    id: '30',
    title: 'Kompaktni Moderni Farmhouse',
    description: 'Pametno dizajnirani kompaktni farmhouse s efikasnim rasporedom prostora, modernim finišima i svim potrebnim sadržajima za udoban porodični život.',
    price: 65,
    sqMeters: 152,
    bedrooms: 3,
    bathrooms: 2,
    imageUrl: 'https://assets.architecturaldesigns.com/cdn-cgi/image/width=3840,quality=75,format=auto,slow-connection-quality=50/plan_assets/383689662/original/51349MM-001-Exterior-Render_1768577880.jpg',
    category: 'Mala Kuća',
    floors: 1,
    garage: true,
    energyClass: 'A',
    kitchen: true,
    terraceArea: 18,
    features: ['Kompaktan raspored', 'Moderna kuhinja', 'Garaža', 'Efikasan prostor', 'Terasa'],
  },
];

export function getProjectById(id: string): HouseDesign | undefined {
  return MOCK_HOUSES.find(h => h.id === id);
}

export function getSimilarProjects(project: HouseDesign, count = 3): HouseDesign[] {
  return MOCK_HOUSES
    .filter(h => h.category === project.category && h.id !== project.id)
    .slice(0, count);
}
